//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markdown.MAML.Resources {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarkdownStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarkdownStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Markdown.MAML.Resources.MarkdownStrings", typeof(MarkdownStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TOPIC.
        /// </summary>
        internal static string AboutTopicFirstHeader {
            get {
                return ResourceManager.GetString("AboutTopicFirstHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accept pipeline input.
        /// </summary>
        internal static string Accept_pipeline_input {
            get {
                return ResourceManager.GetString("Accept_pipeline_input", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accept wildcard characters.
        /// </summary>
        internal static string Accept_wildcard_characters {
            get {
                return ResourceManager.GetString("Accept_wildcard_characters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accepted values.
        /// </summary>
        internal static string Accepted_values {
            get {
                return ResourceManager.GetString("Accepted_values", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        internal static string Aliases {
            get {
                return ResourceManager.GetString("Aliases", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Applicable.
        /// </summary>
        internal static string Applicable {
            get {
                return ResourceManager.GetString("Applicable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](http://go.microsoft.com/fwlink/?LinkID=113216).
        /// </summary>
        internal static string CommonParametersText {
            get {
                return ResourceManager.GetString("CommonParametersText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CommonParameters.
        /// </summary>
        internal static string CommonParametersToken {
            get {
                return ResourceManager.GetString("CommonParametersToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        internal static string Default_value {
            get {
                return ResourceManager.GetString("Default_value", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  (Default).
        /// </summary>
        internal static string DefaultParameterSetModifier {
            get {
                return ResourceManager.GetString("DefaultParameterSetModifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EXAMPLES.
        /// </summary>
        internal static string EXAMPLES {
            get {
                return ResourceManager.GetString("EXAMPLES", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INPUTS.
        /// </summary>
        internal static string INPUTS {
            get {
                return ResourceManager.GetString("INPUTS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        internal static string NOTES {
            get {
                return ResourceManager.GetString("NOTES", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OUTPUTS.
        /// </summary>
        internal static string OUTPUTS {
            get {
                return ResourceManager.GetString("OUTPUTS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter Sets.
        /// </summary>
        internal static string Parameter_Sets {
            get {
                return ResourceManager.GetString("Parameter_Sets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PARAMETERS.
        /// </summary>
        internal static string PARAMETERS {
            get {
                return ResourceManager.GetString("PARAMETERS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RELATED LINKS.
        /// </summary>
        internal static string RELATED_LINKS {
            get {
                return ResourceManager.GetString("RELATED_LINKS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SYNOPSIS.
        /// </summary>
        internal static string SYNOPSIS {
            get {
                return ResourceManager.GetString("SYNOPSIS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SYNTAX.
        /// </summary>
        internal static string SYNTAX {
            get {
                return ResourceManager.GetString("SYNTAX", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This cmdlet supports the following workflow common parameters: -PSParameterCollection, -PSComputerName, -PSCredential, -PSConnectionRetryCount, -PSConnectionRetryIntervalSec, -PSRunningTimeoutSec, -PSElapsedTimeoutSec, -PSPersist, -PSAuthentication, -PSAuthenticationLevel, -PSApplicationName, -PSPort, -PSUseSSL, -PSConfigurationName, -PSConnectionURI, -PSAllowRedirection, -PSSessionOption, -PSCertificateThumbprint, -PSPrivateMetadata, -AsJob, -JobName, and –InputObject. For more information, see about_Workf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkflowParametersText {
            get {
                return ResourceManager.GetString("WorkflowParametersText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WorkflowCommonParameters.
        /// </summary>
        internal static string WorkflowParametersToken {
            get {
                return ResourceManager.GetString("WorkflowParametersToken", resourceCulture);
            }
        }
    }
}
