parameters:
    stageName: ''
    environmentName: ''
    feedCredential: ''

stages:
- stage: ${{ parameters.stageName }}
  displayName: Release Microsoft.PowerShell.PlatyPS to '${{ parameters.stageName }}'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))

  jobs:
  - deployment: Publish_${{ parameters.stageName }}
    displayName: Release to Feed
    pool:
      name: 1ES

    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: nuget

          - pwsh: |
              $package = (Get-ChildItem "$(Pipeline.Workspace)/nuget/Microsoft.PowerShell.PlatyPS.*.nupkg").FullName
              $package
              $vstsCommandString = "vso[task.setvariable variable=NugetPkgPath]${package}"
              Write-Host "sending " + $vstsCommandString
              Write-Host "##$vstsCommandString"
            displayName: Capture downloaded artifact

          - task: NuGetAuthenticate@0
            condition: ne('${{ parameters.feedUrl }}', '')

          - task: NuGetCommand@2
            displayName: 'NuGet push'
            inputs:
              command: push
              packagesToPush: '$(NugetPkgPath)'
              nuGetFeedType: external
              publishFeedCredentials: ${{ parameters.feedCredential }}
              condition: eq('${{ parameters.feedUrl }}', '')
